// examples/react-query/src/usage.tsx
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'

import {
  useCreatePetMutation,
  useDeletePetMutation,
  usePetQuery,
  usePetsQuery,
  useUpdatePetMutation,
} from '../generated/src/features/pets/api'
import type {
  CreatePetRequest,
  PetId,
  UpdatePetRequest,
} from '../generated/src/shared/api/generated/pets/pets.types'

const queryClient = new QueryClient()

type PetsPanelProps = {
  selectedId: PetId
  draft: CreatePetRequest
  edit: UpdatePetRequest
}

// Exercises the generated TanStack Query hooks against the real
// `@tanstack/react-query` runtime: list/detail queries plus create/update/delete
// mutations with their typed inputs and cache invalidation.
function PetsPanel({ selectedId, draft, edit }: PetsPanelProps) {
  const list = usePetsQuery()
  const detail = usePetQuery(selectedId)
  const create = useCreatePetMutation()
  const update = useUpdatePetMutation()
  const remove = useDeletePetMutation()

  if (list.isPending) return <p>Loading pets…</p>
  if (list.isError) return <p>Failed to load pets</p>

  return (
    <div>
      <p>Pets loaded: {list.data ? 'yes' : 'no'}</p>
      <p>Selected pet: {detail.data ? 'found' : 'missing'}</p>
      <button type="button" onClick={() => create.mutate(draft)}>
        Create
      </button>
      <button type="button" onClick={() => update.mutate({ id: selectedId, payload: edit })}>
        Update
      </button>
      <button type="button" onClick={() => remove.mutate(selectedId)}>
        Delete
      </button>
    </div>
  )
}

export function App(props: PetsPanelProps) {
  return (
    <QueryClientProvider client={queryClient}>
      <PetsPanel {...props} />
    </QueryClientProvider>
  )
}

// examples/angular-query/src/usage.ts
import { Component, input } from '@angular/core'

import {
  useCreatePetMutation,
  useDeletePetMutation,
  usePetQuery,
  usePetsQuery,
  useUpdatePetMutation,
} from '../generated/src/features/pets/api'
import type {
  CreatePetRequest,
  PetId,
  UpdatePetRequest,
} from '../generated/src/shared/api/generated/pets/pets.types'

// Exercises the generated Angular Query injectors against the real
// `@tanstack/angular-query-experimental` runtime. The injectors must run in an injection
// context, so they are bound as component fields; this file type-checks that the generated
// signatures line up with the installed library.
@Component({ selector: 'pets-panel', template: '' })
export class PetsPanelComponent {
  readonly selectedId = input.required<PetId>()
  readonly draft = input.required<CreatePetRequest>()
  readonly edit = input.required<UpdatePetRequest>()

  readonly list = usePetsQuery()
  readonly detail = usePetQuery(this.selectedId())
  readonly create = useCreatePetMutation()
  readonly update = useUpdatePetMutation()
  readonly remove = useDeletePetMutation()

  createPet(): void {
    this.create.mutate(this.draft())
  }

  updatePet(): void {
    this.update.mutate({ id: this.selectedId(), payload: this.edit() })
  }

  removePet(): void {
    this.remove.mutate(this.selectedId())
  }
}
